name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Start
        env:
          BOT_API: ${{ vars.BOT_API }}
          GEMINI_API: ${{ vars.GEMINI_API }}
          LIMIT_USE: ${{ vars.LIMIT_USE }}
          NGROK_TOKEN: ${{ vars.NGROK_TOKEN }}
          ROW_X_PAGE: ${{ vars.ROW_X_PAGE }}
          VIDEOG_DB: ${{ vars.VIDEOG_DB }}
        #run: |
        #  echo "env ROW_X_PAGE es ${{ env.ROW_X_PAGE }}"
        #  echo "vars ROW_X_PAGE es ${{ vars.ROW_X_PAGE }}"
        run: python my_script.py