name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Start
        env:
          BOT_API: ${{ secrets.BOT_API }}
          GEMINI_API: ${{ secrets.GEMINI_API }}
          LIMIT_USE: ${{ secrets.LIMIT_USE }}
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          ROW_X_PAGE: ${{ secrets.ROW_X_PAGE }}
          VIDEOG_DB: ${{ secrets.VIDEOG_DB }}
        run: python main.py

#BOT_API
#GEMINI_API
#LIMIT_USE
#NGROK_TOKEN
#ROW_X_PAGE
#VIDEOG_DB