name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      #- name: Install Requirements
      #  run: pip install -r requirements.txt

      - name: Start
        env:
          BOT_API: ${{ env.BOT_API }}
          GEMINI_API: ${{ env.GEMINI_API }}
          LIMIT_USE: ${{ env.LIMIT_USE }}
          NGROK_TOKEN: ${{ env.NGROK_TOKEN }}
          ROW_X_PAGE: ${{ env.ROW_X_PAGE }}
          VIDEOG_DB: ${{ env.VIDEOG_DB }}
        run: echo "ROW_X_PAGE es ${{ env.ROW_X_PAGE }}"